# Setup
theme: jekyll-theme-cayman

title:        RemoteConfig | Android Library for your remote configurations
baseurl:      "/RemoteConfig"
locale:       "it"

# About/contact
author:
  name:       Giuseppe Giacoppo 